### ISSUE TITLE
CDK, formerly Cloud Formation

### ISSUE THREAD

**Issue by TheENGR** [Cyberspace-Citizenship-Coefficient/AWS-Lambdas#6]
### Is your proposal related to a problem?

We need a way to configure this code consistently in the cloud

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by TheENGR** [comment]
@ajaxx this is done correct?

**Comment by ajaxx** [comment]
Changed to CDK and not committed.  So let's not close this yet.

**Comment by ajaxx** [comment]
This has been completed.
