### ISSUE TITLE
Publicly (?) Accessible HTTP Endpoints

### ISSUE THREAD

**Issue by TheENGR** [Cyberspace-Citizenship-Coefficient/AWS-Lambdas#7]
### Is your proposal related to a problem?

(Write your answer here.)

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by ajaxx** [comment]
Endpoints are now exposed with default handlers.

https://439r656kxf.execute-api.us-east-2.amazonaws.com/dev/hello
https://439r656kxf.execute-api.us-east-2.amazonaws.com/dev/infraction
